title: Gumshoe
description: Use a machine learning model to help pick out the relevant documents from a collection
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties:
  relevant:
    title: Relevant Keywords
    type: string
  irrelevant:
    title: Irrelevant Keywords
    type: string
  email:
    title: Email
    type: string
    format: email


